version: "3.1"
services:
  # front:
  #   build: ./front
  #   container_name: front
  #   ports:
  #     - 8080:3000
  #   restart: always
  #   networks:
  #     - backend
  #   depends_on:
  #     - back

  mongo-seed:
    build: ./initdb
    depends_on: 
        - mongodb
        - back
    networks:
      - backend

  back:
    build: ./back
    env_file:
      - .env
    container_name: back
    restart: always
    ports:
      - 8081:8000
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo
    container_name: mongodb
    hostname: 0.0.0.0
    volumes:
      - "./database:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - 0.0.0.0
    ports:
      - "27017:27017"
    expose:
      - "27017"
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge